# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rj

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InitializeStatusFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInitializeStatusFrame(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InitializeStatusFrame()
        x.Init(buf, n + offset)
        return x

    # InitializeStatusFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InitializeStatusFrame
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def InitializeStatusFrameStart(builder): builder.StartObject(1)
def InitializeStatusFrameAddTitle(builder, title): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)
def InitializeStatusFrameEnd(builder): return builder.EndObject()
