# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rj

class StatusFrame(object):
    NONE = 0
    CTREMotorStatusFrame = 1
    PDPStatusFrame = 2
    PCMStatusFrame = 3
    InitializeStatusFrame = 4

